services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PG_DB:-ticketarr}
      POSTGRES_USER: ${PG_USER:-ticketarr}
      POSTGRES_PASSWORD: ${PG_PASS:?Database password required}
    volumes:
      - db_data1:/var/lib/postgresql/data
    networks:
      kasm-dev1:
        ipv4_address: 172.52.0.12

  web:
    image: l3ochan/ticketarr:latest
    env_file:
      - stack.env
    volumes:
      - django_state:/django_state:rw
    environment:
      DEBUG: ${DEBUG:-False}
      POSTGRES_DB: ${PG_DB:-ticketarr}
      TICKETARR_SECRET: ${TICKETARR_SECRET:?Ticketarr secret required}
      POSTGRES_USER: ${PG_USER:-ticketarr}
      POSTGRES_PASSWORD: ${PG_PASS:?Database password required}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_SSLMODE: ${PG_SSL_MODE:-prefer}
      TZ: ${TZ:-UTC}
    # Monte le dossier persistant de l'hôte dans /app du conteneur
    ports:
      - "10000:8000"
    depends_on:
      - db
    # (optionnel) aligne l'UID/GID pour éviter des fichiers root sur l'hôte
    user: "1000:1000"
    networks:
      kasm-dev1:
        ipv4_address: 172.52.0.10


volumes:
  db_data1:
  django_state:
networks: 
  kasm-dev1:
    external: true