# Generated by Django 5.2.5 on 2025-09-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
    ]
