# Generated by Django 5.2.5 on 2025-09-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_project_uniq_project_per_customer'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE tickets_project
                DROP CONSTRAINT IF EXISTS uniq_project_per_customer;
            """,
            reverse_sql=migrations.RunSQL.noop,  # on ne tente pas de la recréer (le champ customer n'existe plus)
        ),
    ]
