# Generated by Django 5.2.5 on 2025-09-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_project_uniq_project_per_customer'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE tickets_project
                DROP CONSTRAINT IF EXISTS uniq_project_per_customer;
            """,
            reverse_sql=migrations.RunSQL.noop,  # on ne tente pas de la recréer (le champ customer n'existe plus)
        ),
        migrations.AddField(
            model_name='comment',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
