# Generated by Django 5.2.5 on 2025-09-10 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_project_uniq_project_per_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE tickets_project
                DROP CONSTRAINT IF EXISTS uniq_project_per_customer;
            """,
            reverse_sql=migrations.RunSQL.noop,  # on ne tente pas de la recréer (le champ customer n'existe plus)
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['client'], name='tickets_tic_client__16e772_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project'], name='tickets_tic_project_ef7556_idx'),
        ),
    ]
